server:
  port: 8082
spring:
  application:
    name: bank
  datasource:
    url: jdbc:mysql://localhost:3306/qadr_micro?zeroDateTimeBehavior=convertToNull
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

info:
  appName: api for all the bank in Nigeria
  version: 1.0