global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8000']
  - job_name: 'bank'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bank:8082']
  - job_name: 'country'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['country:8081']