server:
  port: 8081
spring:
  zipkin:
    baseUrl: http://localhost:9411/
  application:
    name: country
  datasource:
    url: jdbc:mysql://localhost:3306/qadr_micro
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
eureka:
  instance:
    preferIpAddress: true
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

info:
  appName: api for all countries in the world
  version: 1.0