server:
  port: 8000
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/clients
      username: root
      password: root
  zipkin:
    baseUrl: http://localhost:9411/
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 5s
  application:
    name: gateway
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
info:
  appName: gateway to microservices network
  version: 1.0