apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-deployment
  labels:
    app: country
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country
  template:
    metadata:
      labels:
        app: country
    spec:
      containers:
        - name: country
          image: abdqadr/country:2.0
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: microservices-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-configmap
                  key: MYSQLDB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: microservices-configmap
                  key: MYSQLDB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: microservices-configmap
                  key: MYSQLDB_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: microservices-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: country-service
spec:
  selector:
    app: country
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081